{
 "title": "Service",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Service metrics (Response)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(prediction_response_sum[30s])) / sum(increase(prediction_response_count[30s]))",
     "legendFormat": "Predictions Output"
    },
    {
     "expr": "sum(increase(score_response_sum[30s])) / sum(increase(score_response_count[30s]))",
     "legendFormat": "Predictions Scores"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(prediction_latency_sum[30s])) / sum(increase(prediction_latency_count[30s]))",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Service metrics (Totals)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(prediction_total[5m])", "legendFormat": "Predictions total rate" },
    { "expr": "rate(model_info_total[5m])", "legendFormat": "Model information total rate" }
   ]
  }
 ]
}